obstacle_range: 1.0
raytrace_range: 3.0
robot_radius: 0.15
inflation_radius: 0.15
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}


